version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: devtraining-2024
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtraining

  dbtest:
    image: postgres:latest
    container_name: test-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=devtraining
